# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ee1cd05f64786fa1f63467a0208a3f95e23d41d735b1c7008fbff90cb14af7087394f7dd72f89e4b7a87bcdca61f80c2b114fee11c6b912914d41267037d568

test:
  secret_key_base: c2c203d5abaceb7eefd621cf16d8da4030b9a208bfe6bc9dc757be7f1595520cb5e6c1d7b30688a39a513ed28efaaf2841d1ec32727950f55886295e6ece8920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
